<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>Piko.Runtime.Client</AssemblyName>
    <RootNamespace>Piko.Runtime</RootNamespace>
    <Version>0.2.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Piko.Context\Piko.Context.csproj" />
  </ItemGroup>
</Project>
