<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PikoVersion>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)release-version.txt').Trim())</PikoVersion>
    <Version>$(PikoVersion)</Version>
    <AssemblyVersion>$(PikoVersion).0</AssemblyVersion>
    <FileVersion>$(PikoVersion).0</FileVersion>
  </PropertyGroup>
</Project>

