<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Piko.World\Piko.World.csproj" />
    <ProjectReference Include="..\Piko.World.Windows\Piko.World.Windows.csproj" />
  </ItemGroup>
</Project>
